language: ruby
os:
  - linux
  - osx
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./testscript.sh          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./testscript1.sh          ; fi
