
version: 2
jobs:
  one:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run: sudo pip install --upgrade pip
      - run: sudo pip install qhue
      - run: echo "hello world!"
  two:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - run: echo "hopefully this ran sequentially"

workflows:
  version: 2
  one-and-two:
    jobs:
      - one:
          type: approval
      - two:
          requires:
            - one
