
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run: sudo pip install --upgrade pip
      - run: pip install qhue
      - run: echo "hello world!"
